import { ASSETS } from '../data/assets.js';
import { CONTACT_LINKS } from '../data/contact.js';

function resumeLink() {
  return CONTACT_LINKS.resume ? `<a class="folio-link" href="${CONTACT_LINKS.resume}" download>Download résumé ↓</a>` : '';
}
export function aboutSheet() {
  return `<div class="profile-heading"><p class="file-label">Personal file / Gerikah Alday</p><h3>A creative eye.<br />A technical foundation.</h3></div><div class="profile-layout"><figure class="profile-portrait"><img src="${ASSETS.portrait}" alt="Gerikah Alday in a dark suit and tie" width="508" height="508" loading="lazy" /><figcaption class="file-label">Gerikah Alday · Philippines</figcaption></figure><div class="profile-copy"><p class="file-label">Designer / developer / documentarian</p><h4>I work where design meets <em>logic.</em></h4><p>I design for clarity, structure, and the moment an idea becomes usable.</p><p>I’m Gerikah Alday, a UI/UX designer with a Computer Engineering background. I enjoy turning complex workflows into clear interfaces, from drone-control dashboards to pixel game experiences.</p><p>My experience also includes full-stack web and mobile development, which helps me think about how a design will work beyond the screen.</p><ol class="approach-index"><li>Make complexity legible.</li><li>Connect structure with feeling.</li><li>Design with implementation in mind.</li></ol>${resumeLink()}</div></div><div class="profile-record"><p class="file-label">Background</p><div><h4>Freelance Technical Documentation Assistant</h4><p>Fiverr · Dec 30 2022 - January 2026</p><p>Delivered flowcharts, pseudocode, wireframes, and UI/UX documentation for 3+ years of client projects across academic and software development contexts.</p><ul><li>Assisted clients with logic design, system analysis, and front-end structure planning for web-based applications.</li><li>Maintained consistent positive client feedback, demonstrating ability to translate technical requirements into clear written and visual documentation.</li></ul><a class="folio-link" href="#flowcharts-process-mapping">View related work ↗</a></div><div><h4>Computer Engineering</h4><p>Polytechnic University of the Philippines</p><p>Expected graduation: September 2026</p></div></div><div class="profile-tools"><p class="file-label">Selected tools</p><dl><dt>Design &amp; prototyping</dt><dd>Figma / Framer</dd><dt>Development</dt><dd>React / TypeScript / Node.js / Supabase</dd><dt>Workflow &amp; version control</dt><dd>VS Code / GitHub</dd></dl></div>`;
}
export function contactSheet() {
  return `<p class="file-label">End of file / Start of something</p><h3 class="contact-sheet-title">Let’s make<br />something<br /><span>worth using.</span></h3><div class="contact-sheet-bottom"><div><p class="contact-note">I’m open to UI/UX design opportunities and freelance projects. If you’re looking for someone who enjoys both the creative and technical sides of digital work, I’d love to connect.</p><a class="contact-email" href="mailto:${CONTACT_LINKS.email}">${CONTACT_LINKS.email} ↗</a><div class="contact-networks"><a href="${CONTACT_LINKS.linkedin}">LinkedIn ↗</a><a href="${CONTACT_LINKS.github}">GitHub ↗</a></div></div><img class="contact-mark" src="${ASSETS.logo}" alt="" width="160" height="160" loading="lazy" /></div><div class="contact-colophon"><p class="file-label">© ${new Date().getFullYear()} Gerikah Alday</p><p class="file-label">Based in Manila, Philippines.</p><p class="file-label">Designed with intention.</p><a href="#top" data-back-top>Back to top ↑</a></div>`;
}
