import { build } from 'esbuild';
import { cp, mkdir, readFile, writeFile, stat, rm } from 'node:fs/promises';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { join, resolve, relative } from 'node:path';
import { portfolioFolders } from '../src/data/folders.js';
const root = fileURLToPath(new URL('../', import.meta.url));
const output = resolve(root, 'dist');
const scratch = resolve(root, '.preview');
await mkdir(scratch, { recursive: true });
const renderer = join(scratch, 'render-build.mjs');
await build({ entryPoints: [join(root, 'src/render.jsx')], outfile: renderer, bundle: true, platform: 'node', format: 'esm', packages: 'external', jsx: 'automatic' });
const { renderPortfolio } = await import(pathToFileURL(renderer).href + '?build=' + Date.now());
const body = renderPortfolio();
const documents = body + portfolioFolders.map(folder => folder.fullContent || '').join('');
const assets = new Set(['/assets/background%20image.png', '/assets/favicon.png']);
for (const match of documents.matchAll(/(?:src|href)="(\/assets\/[^"#]+)"/g)) assets.add(match[1]);
for (const folder of portfolioFolders) for (const image of folder.previewImages || []) assets.add(image.src);
const fonts = await readFile(join(root, 'assets/fonts/fonts.css'), 'utf8');
for (const match of fonts.matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)) assets.add(match[1]);
for (const asset of assets) await stat(join(root, decodeURIComponent(asset)));
// The build owns only the resolved dist directory; clear stale route output.
if (relative(root, output) !== 'dist') throw new Error('Invalid build output directory');
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
for (const name of ['styles.css', 'folder.css', 'assets']) await cp(join(root, name), join(output, name), { recursive: true });
await build({ entryPoints: [join(root, 'src/entry.jsx')], outfile: join(output, 'app.js'), bundle: true, format: 'esm', minify: true, jsx: 'automatic', define: { 'process.env.NODE_ENV': '"production"' }, legalComments: 'linked' });
const template = await readFile(join(root, 'index.html'), 'utf8');
await writeFile(join(output, 'index.html'), template.replace('<body>', '<body class="folder-theme">').replace('<div id="app"></div>', '<div id="app">' + body + '</div>'));
console.log('Built one React portfolio page; verified ' + assets.size + ' original assets.');
